---
title: "sampling_viz"
output: html_document
---
```{r fig.width=10, fig.height = 9}
source("general_functions.R")

source("/Users/Anusha/Documents/GitHub/LandGenSamp/p3_methods/sitesampling/sitesampling_functions.R")
i=400

nsites <- c(9, 16, 25)
sampstrats <- c("grid", "rand", "envgeo", "equi")
par(mfrow=c(length(nsites), length(sampstrats)), pty="s", mar = rep(2, 4))
for(i in 1:2){
    gsd_df <- get_data(i, params = params, "gsd")
    for(nsite in nsites){
      for(sampstrat in sampstrats){
        #subsample from data based on sampling strategy and number of samples
        subIDs <-  get_samples(params[i,], params, sampstrat, nsite)
        subgsd_df <- gsd_df[subIDs,]
        plot(subgsd_df$x, subgsd_df$y, xlim = c(0,40), ylim = c(0,40), main = paste0(nsite," / ", sampstrat),
             xlab = "", ylab = "", pch = 19, col = "#756fd6")
      }
    }
  }

```

```{r}
i=4
sampstrat = "equi"
nsite = 9
subIDs <-  get_samples(params[i,], params, sampstrat, nsite)
subgsd_df <- gsd_df[subIDs,]
plot(subgsd_df$x, subgsd_df$y, xlim = c(0,40), ylim = c(0,40), main = paste0(nsamp," / ", sampstrat),
             xlab = "", ylab = "", pch = 19, col = "#756fd6")
```

```{r fig.width = 10, fig.height = 9}
nsites <- c(9, 16, 25)
sampstrats <- c("grid", "rand", "envgeo", "equi")
par(mfrow=c(length(nsites), length(sampstrats)), pty="s", mar = rep(2, 4))
i=490
gsd_df <- get_data(i, params = params, "gsd")


envpc <- prcomp(gsd_df[, c("env1","env2")])
envpc1 <- envpc$x[,1]
palz <- turbo(100)
envcol <- palz[as.numeric(cut(envpc1, breaks = 100))]
names(envcol) <- rownames(gsd_df)


par(mfrow=c(length(nsites), length(sampstrats)), pty="s", mar = rep(2, 4))
for(nsite in nsites){
  for(sampstrat in sampstrats){
    #subsample from data based on sampling strategy and number of samples
    subIDs <-  get_samples(params[i,], params, sampstrat, nsite)
    subgsd_df <- gsd_df[subIDs,]
    plot(subgsd_df$x, subgsd_df$y, xlim = c(0,40), ylim = c(0,40), main = paste0(nsite," / ", sampstrat),
             xlab = "", ylab = "", pch = 19, col = envcol[subIDs])
    }
  }

```

