---
title: "loci4"
output: html_document
date: "2023-06-01"
---
```{r}
library(here)
library(tidyverse)
library(lfmm)
library(vcfR)
source(here("general_functions.R"))
source(here("p3_methods", "GEA_functions.R"))
```

```{r}
ggfacet <- function(df, cols, nrow = 1) {
  df2 <- 
    df %>% 
    pivot_longer(all_of(cols), names_to = "name", values_to = "value") %>%
    mutate(name = factor(name, levels = cols))
  gg <- 
    ggplot(data = df2, aes(x = x, y = y, col = value)) + 
    geom_point() + 
    facet_wrap(~name, nrow = nrow) 
  return(gg)
}
```

```{r}
gsd2 <- get_gsd("p1_gnxsims/gnx/GNX_mod-loci4_K2_phi100_m25_seed1_H50_r30/it-0/spp-spp_0/mod-loci4_K2_phi100_m25_seed1_H50_r30_it-0_t-1000_spp-spp_0.csv")
gen2 <- get_gen("p1_gnxsims/gnx/GNX_mod-loci4_K2_phi100_m25_seed1_H50_r30/it-0/spp-spp_0/mod-loci4_K2_phi100_m25_seed1_H50_r30_it-0_t-1000_spp-spp_0.vcf")
```

```{r}
gsd2 <- get_gsd("p1_gnxsims/gnx/GNX_mod-loci4_K2_phi100_m100_seed1_H50_r30/it-0/spp-spp_0/mod-loci4_K2_phi100_m100_seed1_H50_r30_it-0_t-1000_spp-spp_0.csv")
gen2 <- get_gen("p1_gnxsims/gnx/GNX_mod-loci4_K2_phi100_m100_seed1_H50_r30/it-0/spp-spp_0/mod-loci4_K2_phi100_m100_seed1_H50_r30_it-0_t-1000_spp-spp_0.vcf")
```


```{r}
s <- sample(nrow(gsd2), 1000)
gen <- gen2[s,]
gsd <- gsd2[s,]
loci_df = data.frame(trait1 = 1:2, trait2 = 3:4)
lfmm_result <- run_lfmm(gen, gsd, loci_df = loci_df, Kvals = 1:20)

df <- bind_cols(gsd, gen/2)
ggfacet(df, c("env1", "z1", "0_0", "0_1", 
              "env2", "z2", "0_2", "0_3",
              "0_5", "0_6", "0_7", "0_8"), nrow = 3) + 
  theme_bw() + 
  coord_equal() +
  scale_color_viridis_c(option = "viridis")

ggfacet(df, c("env2", "z2", "0_2", "0_7"), nrow = 3) + 
  theme_bw() + 
  coord_equal() +
  scale_color_viridis_c(option = "viridis")


lfmm_result <- algatr::lfmm_do_everything(gen, gsd[,c("env1", "env2")], coords = gsd[,c("x", "y")], K = 95)


rda_result <- algatr::rda_do_everything(gen, env = gsd[,c("env1", "env2")], coords = gsd[,c("x", "y")], model = "full")

```




# tests
- fewer loci, low m
- fewer loci, high m
- same loci, one env
- california env
- monogenic? 

```{r}
library(NLMR)
```

```{r}
fbm <- nlm_fbm(100,100)
mpd <- nlm_mpd(100,100)
plot(mpd)
plot(fbm)

#CHOOSE FBM because brownian motion makes more sense
set.seed(42)


future::plan(future::multisession, workers = 3)
fbm <- raster::stack(furrr::future_map(1:10000, ~nlm_fbm(100, 100), 
                                .options = furrr::furrr_options(seed = TRUE, packages = c("NLMR", "raster")),
                                .progress = TRUE))
future::plan("sequential")

raster::extent(fbm) <- c(0, 100, -100, 0)
#cor <- raster::layerStats(fbm, 'pearson', na.rm=T)
#raster::layerStats(fbm_bin[[1:2]], 'pearson', na.rm=T)
#hist(cor$`pearson correlation coefficient`)
fbm_bin <- fbm
fbm_bin[fbm > 0.55] <- 1
fbm_bin[fbm < 0.45] <- 0
fbm_bin[fbm_bin != 0 & fbm_bin != 1] <- 0.5
plot(fbm_bin)

fbme <- data.frame(raster::extract(fbm, gsd_df[,c("x", "y")]))
df3 <- data.frame(gsd_df, raster::extract(fbm_bin,gsd_df[,c("x", "y")] ))
df3$env1 <- fbme$layer.2
df3$env2 <- fbme$layer.1

plot(raster::stack(fbm[[1]], fbm_bin[[1]]))

summary(lm(df3$layer.1 ~ df3$env1))
summary(lm(df3$layer.2 ~ df3$env2))

test <- run_lfmm(df3[,grepl("layer", colnames(df3))], df3, K = 19, loci_df = data.frame(trait1 = 1, trait2 = 2))

library(algatr)

lfmm_result <- lfmm_do_everything(gen = df3[,grepl("layer", colnames(df3))], env = df3[,c("env1", "env2")])


```

# 1 trait
```{r}
gsd2 <- get_gsd("p1_gnxsims/gnx/GNX_mod-trait1_K2_phi100_m100_seed1_H50_r30/it-0/spp-spp_0/mod-trait1_K2_phi100_m100_seed1_H50_r30_it-0_t-1000_spp-spp_0.csv")
gen2 <- get_gen("p1_gnxsims/gnx/GNX_mod-trait1_K2_phi100_m100_seed1_H50_r30/it-0/spp-spp_0/mod-trait1_K2_phi100_m100_seed1_H50_r30_it-0_t-1000_spp-spp_0.vcf")
```


```{r}
s <- sample(nrow(gsd2), 200)
gen <- gen2[s,]
gsd <- gsd2[s,]
lfmm_result <- algatr::lfmm_do_everything(gen, env = gsd[,c("env1")], coords = gsd[,c("x", "y")], K_selection = "tracy_widom")
lfmm_result$cand_snps

rda_result <- algatr::rda_do_everything(gen, env = gsd[,c("env1")], coords = gsd[,c("x", "y")], model = "full")
rda_result$rda_snps


df <- bind_cols(gsd, gen/2)
ggfacet(df, c("env1", "z1", "0_0", "0_1", "0_2", "0_3",
              "0_5", "0_6", "0_7", "0_8", "0_9", "0_10"), nrow = 2) + 
  theme_bw() + 
  coord_equal() +
  scale_color_viridis_c(option = "viridis")
```
