---
title: "clines"
output: html_document
date: "2022-12-02"
---

# Causal Clines 

```{r,fig.width=16, fig.height=7}
df <- read.csv(here("p3_methods", "outputs", "cline_results.csv"))

summary_df_full <- df %>% 
  filter(sampstrat == "full") %>% 
  dplyr::select(K, phi, m, H, r, prop, cor) %>%
  # convert from wide to long format
  pivot_longer(c(K, phi, m, H, r)) %>%
  # turn value into numeric from factor
  mutate(value = as.numeric(as.character(value))) %>%
  # group by the parameter (name)
  group_by(name) %>% 
  # create new low/high variable (the group_by name makes sure this is done for each parameter seperately)
  mutate(low_high = case_when(
      value == min(value) ~ "low",
      value == max(value) ~ "high",
      TRUE ~ "NA")) %>% 
  # group again by the new group (low_high), the param (name), and nsamp/sampstrat
  group_by(name, low_high) %>%
  # summarize by group
  summarise(prop = mean(prop), cor = mean(cor))

summary_df_full

summary_hplot(df, "prop")
summary_hplot(df, "cor")
```

```{r}
summary_df_full <- df %>% 
  filter(sampstrat == "full") %>% 
  dplyr::select(K, phi, m, H, r, prop_cline) %>%
  # convert from wide to long format
  pivot_longer(c(K, phi, m, H, r)) %>%
  # turn value into numeric from factor
  mutate(value = as.numeric(as.character(value))) %>%
  # group by the parameter (name)
  group_by(name) %>% 
  # create new low/high variable (the group_by name makes sure this is done for each parameter seperately)
  mutate(low_high = case_when(
      value == min(value) ~ "low",
      value == max(value) ~ "high",
      TRUE ~ "NA")) %>% 
  # group again by the new group (low_high), the param (name), and nsamp/sampstrat
  group_by(name, low_high) %>%
  # summarize by group
  summarise(mean = mean(prop_cline))
```
