---
title: "analysis_megatable"
output: html_document
date: "2022-10-18"
---
```{r}
library(tidyverse)
library(here)
library(gt)
```

```{r}
format_csv <- function(path){
    read.csv(path) %>%
    mutate(path = str_extract(basename(path), '.*(?=\\.csv)')) %>%
    tidyr::separate(path, c("method", "sampling", "stat", "type"))
}

p4path <- here("p4_analysis", "outputs")


df <- list.files(p4path, full.names = TRUE, pattern = "*_lmer.csv") %>%
  map(format_csv) %>%   
  reduce(rbind) 
```

```{r}

table_df <- 
  df %>%
  as_tibble() %>%
  filter(stat != "geoerr" & stat != "enverr") %>%
  filter(Pr..F. < 0.05) %>%
  dplyr::select(method, stat, sampling, FixedEffects, Variable) %>%
  #filter(Variable != "sampstrat") %>%
  spread(Variable, FixedEffects) %>%
  select(method,
      stat,
      sampling,
      `Sample number`,
      `Population size`, 
      `Migration`,
      `Selection strength`,
      `Spatial autocorrelation`,
      `Environmental correlation`)
  
write.csv(table_df, here("p4_analysis", "megatable.csv"), row.names = FALSE)

```


```{r}
table_df %>%
  filter(sampling == "individual" | sampling == "site") %>% 
  gt(
    rowname_col = "stat",
    groupname_col = "method"
    ) %>%
  cols_label(
      method = "Method",
      stat = "Statistic",
      sampling = "Sampling type",
      `Sample number` = "Sample number",
      `Population size` = "Population\nsize", 
      `Selection strength` = "Selection\nstrength",
      `Migration` = "Migration",
      `Spatial autocorrelation` = "Spatial\nautocorrelation",
      `Environmental correlation` = "Environmental\ncorrelation"
    ) %>%
  row_group_order(
    groups = c("LFMM", "RDA", "GDM", "MMRR")
    ) %>%
  fmt_number(
    columns = c(4:9),
    decimals = 4,
    suffixing = TRUE
    ) %>%
  data_color(
    columns = 4:9,
    colors = scales::col_numeric(
      palette = c("#8787fcff","#fcfcfcff", "#f6b26bff"),
      domain = c(-0.12,0.12),
      na.color = "white",
    )
  ) %>%
  sub_missing(
    columns = everything(),
    rows = everything(),
    missing_text = "n.s."
    ) %>%
  cols_width(
    4:9 ~ px(120)
  ) %>%
  tab_spanner(
    label = "Population Genetics",
    columns = 5:7
  ) %>%
  tab_spanner(
    label = "Landscape",
    columns = 8:9
  ) %>%
  tab_spanner(
    label = "Sampling",
    columns = 3:4
  )


  
```


```{r}

df <- list.files(p4path, full.names = TRUE, pattern = "*_tukey.csv") %>%
  map(format_csv) %>%   
  reduce(rbind) 

df$estimate[df$p.value > 0.05] <- NA
table_df <- 
  df %>%
  filter(sampling == "site" | sampling == "individual") %>%
  select(contrast, estimate, method, stat, sampling) %>%
  #filter(Variable != "sampstrat") %>%
  spread(contrast, estimate) %>%
  select(sampling, method, stat, 
         "EG - G", "EG - R", "EG - T", 
         "G - R", "G - T", 
         "EG - EQ", "EQ - R",
         "R - T") %>%
  group_by(sampling) %>%
  group_split()

table_df_ind <- table_df[[1]] %>% select(-sampling, -"EG - EQ", -"EQ - R")
table_df_site <- table_df[[2]] %>% select(-sampling, -"EG - G", -"G - R", -"G - T", -"R - T", -"EG - T")
  
write.csv(table_df_ind, here("p4_analysis", "tukey_ind.csv"), row.names = FALSE)

write.csv(table_df_site, here("p4_analysis", "tukey_site.csv"), row.names = FALSE)

```


```{r}

table_df_ind %>%
  gt(
    rowname_col = "stat",
    groupname_col = "method"
    ) %>%
  row_group_order(
    groups = c("LFMM", "RDA", "GDM", "MMRR")
    ) %>%
  cols_label(
      method = "Method",
      stat = "Statistic"
    ) %>% 
  fmt_number(
    columns = c(3:8),
    decimals = 3,
    suffixing = TRUE
    ) %>%
  gtExtras::gt_hulk_col_numeric(
    c(3:8), 
    trim = TRUE, 
    domain = c(-0.06,0.06),
    na.color = "white"
    ) %>%
  sub_missing(
    columns = everything(),
    rows = everything(),
    missing_text = "n.s."
    ) %>%
  cols_width(
    c(3:8) ~ px(70)
  ) 

```

```{r}

table_df_site %>%
  gt(
    rowname_col = "stat",
    groupname_col = "method"
    ) %>%
  row_group_order(
    groups = c("LFMM", "RDA", "GDM", "MMRR")
    ) %>%
  cols_label(
      method = "Method",
      stat = "Statistic"
    ) %>% 
  fmt_number(
    columns = c(3:5),
    decimals = 3,
    suffixing = TRUE
    ) %>%
  gtExtras::gt_hulk_col_numeric(
    c(3:5), 
    trim = TRUE, 
    domain = c(-0.09,0.09),
    na.color = "white"
    ) %>%
  sub_missing(
    columns = everything(),
    rows = everything(),
    missing_text = "n.s."
    ) %>%
  cols_width(
    c(3:5) ~ px(70)
  ) 
```