#this script un-nests the data generated by gnx and stores it in a new folder
#it also moves the stats and t0 data into a seperate folder
#in the future, I may just want to remove the t0 data because it is not used in anything and takes up space
#for now I am keeping it just for posterity and because I am a hoarder

#create temp directory for nested data
mkdir -p data

#create final dir for unnested data
mkdir -p LGS_data

#move all folders generated by GNX into the temp dir
mv GNX* data

#find all of the files in the nested folders and transfer them to the final dir
find data -type f -print0 | xargs -0 mv -t LGS_data
#note: this will remove the nested structure permanently
#if you just want to copy the data, change mv to cp
#however, these files are very large so you probably don't want to do that if you can

#remove the temp directory
rm -r data

#find all the files in nnloci and move them to the final dir
find nnloci -type f -print0 | xargs -0 mv -t LGS_data

#move into the final dir
mv LGS_data

#create a dir to move the stats into
mkdir -p stats

#move all the stats data into the new dir
mv *HET* stats
mv *MAF* stats
mv *OTHER_STATS* stats

#create a dir for the t0 data
mkdir t0_data

#move t0 data into the new dir
#NOTE - I didn't use *t-0* as the pattern because this would move all the it-0 files
mv *_t-0_* t0_data

#done!
