---
title: "analysis_GEA"
output: github_document
---
```{r, warning=FALSE, message=FALSE}
library("here")
library("sjPlot")
library("dplyr")
library("lme4")
library("viridis")
library("lmerTest")
library("ggplot2")
library("gridExtra")
library("gt")

source("analysis_functions.R")
```

# 1. LFMM 

## 1.1 Individual sampling 

### 1.1.1 Summary plots

```{r, fig.width=20, fig.height=7}
lfmm_ind <- format_lfmm(here(dirname(getwd()), "p3_methods", "outputs", "lfmm_indsampling_results.csv"))


summary_hplot(lfmm_ind, "K.1", colpal = "turbo")
summary_hplot(lfmm_ind, "TPRCOMBO", colpal = "plasma")
summary_hplot(lfmm_ind, "FDRCOMBO", colpal = "viridis", direction = -1)
```

### 1.1.2 Model summaries

```{r}
run_lmer(lfmm_ind, "TPRCOMBO", table_main = "True Positive Rate")
run_lmer(lfmm_ind, "FDRCOMBO", table_main = "False Discovery Rate")
```

### 1.1.3 Megaplots
```{r, fig.width = 30, fig.height=15}
MEGAPLOT(lfmm_ind, "K.1", colpal = "turbo")
MEGAPLOT(lfmm_ind, "TPRCOMBO", colpal = "plasma")
MEGAPLOT(lfmm_ind, "FDRCOMBO", colpal = "viridis", direction = -1)
```

## 1.2 Site sampling 

### 1.2.1 Summary plots

```{r, fig.width=20, fig.height=7}
lfmm_site <- format_lfmm(here(dirname(getwd()), "p3_methods", "outputs", "lfmm_sitesampling_results.csv"))

summary_hplot(lfmm_site, "K.1", colpal = "turbo")
summary_hplot(lfmm_site, "TPRCOMBO", colpal = "plasma")
summary_hplot(lfmm_site, "FDRCOMBO", colpal = "viridis", direction = -1)
```

### 1.2.2 Model summaries

```{r}
run_lmer(lfmm_site, "TPRCOMBO", table_main = "True Positive Rate")
run_lmer(lfmm_site, "FDRCOMBO", table_main = "False Discovery Rate")
```

### 1.2.3 Megaplots
```{r, fig.width = 30, fig.height=15}
MEGAPLOT(lfmm_site, "K.1", colpal = "turbo")
MEGAPLOT(lfmm_site, "TPRCOMBO", colpal = "plasma")
MEGAPLOT(lfmm_site, "FDRCOMBO", colpal = "viridis", direction = -1)
```

# 2. RDA 

## 2.1 Individual sampling 

### 2.1.1 Summary plots

```{r, fig.width=20, fig.height=7}
rda_ind <- format_rda(here(dirname(getwd()), "p3_methods", "outputs", "rda_indsampling_results.csv"))

summary_hplot(rda_ind, "TPRCOMBO", colpal = "plasma")
summary_hplot(rda_ind, "FDRCOMBO", colpal = "viridis", direction = -1)
```

### 2.1.2 Model summaries

```{r}
run_lmer(rda_ind, "TPRCOMBO", table_main = "True Positive Rate")
run_lmer(rda_ind, "FDRCOMBO", table_main = "False Discovery Rate")
```

### 1.1.3 Megaplots
```{r, fig.width = 30, fig.height=15}
MEGAPLOT(rda_ind, "TPRCOMBO", colpal = "plasma")
MEGAPLOT(rda_ind, "FDRCOMBO", colpal = "viridis", direction = -1)
```

## 2.2 Site sampling 

### 2.2.1 Summary plots

```{r, fig.width=20, fig.height=7}
rda_site <- format_rda(here(dirname(getwd()), "p3_methods", "outputs", "rda_sitesampling_results.csv"))

summary_hplot(rda_site, "TPRCOMBO", colpal = "plasma")
summary_hplot(rda_site, "FDRCOMBO", colpal = "viridis", direction = -1)
```

### 2.2.2 Model summaries

```{r}
run_lmer(rda_site, "TPRCOMBO", table_main = "True Positive Rate")
run_lmer(rda_site, "FDRCOMBO", table_main = "False Discovery Rate")
```

### 2.2.3 Megaplots
```{r, fig.width = 30, fig.height=15}
MEGAPLOT(rda_site, "TPRCOMBO", colpal = "plasma")
MEGAPLOT(rda_site, "FDRCOMBO", colpal = "viridis", direction = -1)
```