---
title: "analysis_tests"
output: html_document
---


```{r}
library("dplyr")
library("car")
library("lsmeans")
library("lme4")
library("viridis")
library("lmerTest")
library("ggplot2")
library("gridExtra")
library("MuMIn")
library("emmeans")
library("effects")
library("here")

BuRd <- c("#2066AC", "#4392C2", "#92C4DE", "#D1E5F0", "#F7F7F7", "#FDDBC6", "#F4A581", "#D5604C", "#B2182B")
BlueRed <- colorRampPalette(BuRd, interpolate="linear")

install.packages("ggplot2")
```


#Analysis

```{r}
#number of points to sample
nsamp <- c(36, 81, 144, 225, 2000)
#sampling strategies
sampstrat <- c("rand", "grid", "trans", "envgeo", "full")

#Create dataframe with all variable combos
params_full_samp <- expand.grid(K = c(1, 2), 
                      phi = c(0.1, 0.5),
                      m = c(0.25, 1.0),
                      seed = c(1, 2, 3),
                      H = c(0.05 , 0.5),
                      r = c(0.3, 0.6),
                      nsamp = nsamp[-5],
                      sampstrat = sampstrat[-5],
                      it = 0:9)

params_full_full <- expand.grid(K = c(1, 2), 
                      phi = c(0.1, 0.5),
                      m = c(0.25, 1.0),
                      seed = c(1, 2, 3),
                      H = c(0.05 , 0.5),
                      r = c(0.3, 0.6),
                      nsamp = nsamp[5],
                      sampstrat = sampstrat[5],
                      it = 0:9)

params_full <- rbind(params_full_samp, params_full_full)
dim(params_full)


df <- read.csv("/Users/Anusha/Documents/GitHub/LandGenSamp/p3_methods/outputs/mismatch_results.csv")

```
```{r fig.width=20, fig.height=7}

summary_hplot(df, "mismatch", full = TRUE)

df$eff_mismatch <- df$phi * df$mismatch

ggplot(df[df$sampstrat == "full", ], aes(x = eff_mismatch, fill = factor(phi))) +
  geom_boxplot()

df %>% filter(sampstrat == "full") %>% group_by(phi, K, m, r, H) %>% summarise(mean(abs(mismatch)))


```

