---
title: "analysis_megatable"
output: html_document
date: "2022-10-18"
---
```{r}
library(tidyverse)
library(here)
library(gt)

source(here("p4_analysis", "analysis_functions.R"))
source(here("general_functions.R"))
```

```{r}
format_csv <- function(path){
    read.csv(path) %>%
    mutate(path = str_extract(basename(path), '.*(?=\\.csv)')) %>%
    tidyr::separate(path, c("method", "sampling", "stat", "type"))
}
p4path <- here("p4_analysis", "outputs")

df <- list.files(p4path, full.names = TRUE, pattern = "*_lmer.csv") %>%
  map(format_csv) %>%   
  bind_rows() %>%
  filter(stat != "geocoefferr" & stat != "envcoefferr") %>%
  mutate(method = toupper(method),
         sampling = case_when(sampling == "indsampling" ~ "individual",
                              sampling == "sitesampling" ~ "site",
                              TRUE ~ sampling),
         stat = map_chr(stat, make_pretty_names))

```

```{r}

table_df <- 
  df %>%
  as_tibble() %>%
  filter(Pr..F. < 0.05 | is.na(Pr..F.)) %>%
  dplyr::select(method, stat, sampling, FixedEffects, Variable) %>%
  #filter(Variable != "sampstrat") %>%
  spread(Variable, FixedEffects) %>%
  dplyr::select(
    method,
    stat,
    sampling,
    `Sample number`,
    `Population size`,
    `Migration`,
    `Selection strength`,
    `Spatial autocorrelation`,
    `Environmental correlation`
  ) %>% 
   mutate(method = toupper(method),
         sampling = case_when(grepl("ind", sampling) ~ "individual",
                              grepl("site", sampling) ~ "site",
                              TRUE ~ sampling),
         stat = map_chr(stat, make_pretty_names)) %>%
  mutate()
  
write.csv(table_df, here("p4_analysis", "megatable.csv"), row.names = FALSE)

```


```{r}
table_df %>%
  filter(sampling == "individual" | sampling == "site") %>% 
  gt(
    rowname_col = "stat",
    groupname_col = "method"
    ) %>%
  cols_label(
      method = "Method",
      stat = "Statistic",
      sampling = "Sampling type",
      `Sample number` = "Sample number",
      `Population size` = "Population\nsize", 
      `Selection strength` = "Selection\nstrength",
      `Migration` = "Migration",
      `Spatial autocorrelation` = "Spatial\nautocorrelation",
      `Environmental correlation` = "Environmental\ncorrelation"
    ) %>%
  row_group_order(
    groups = c("LFMM", "RDA", "MMRR", "GDM")
    ) %>%
  fmt_number(
    columns = c(4:9),
    decimals = 4,
    suffixing = TRUE
    ) %>%
  data_color(
    columns = 4:9,
    colors = scales::col_numeric(
      palette = c("#8787fcff","#fcfcfcff", "#f6b26bff"),
      domain = c(-0.40,0.40),
      na.color = "white",
    )
  ) %>%
  sub_missing(
    columns = everything(),
    rows = everything(),
    missing_text = "n.s."
    ) %>%
  cols_width(
    4:9 ~ px(120)
  ) %>%
  tab_spanner(
    label = "Population Genetics",
    columns = 5:7
  ) %>%
  tab_spanner(
    label = "Landscape",
    columns = 8:9
  ) %>%
  tab_spanner(
    label = "Sampling",
    columns = 3:4
  )


  
```


```{r}

df <- 
  list.files(p4path, full.names = TRUE, pattern = "*_tukey.csv") %>%
  map(format_csv)  %>%   
  bind_rows() %>%
  filter(stat != "geocoefferr" & stat != "envcoefferr") %>%
  mutate(method = toupper(method),
         sampling = case_when(grepl("ind", sampling) ~ "individual",
                              grepl("site", sampling) ~ "site",
                              TRUE ~ sampling),
         stat = map_chr(stat, make_pretty_names))

df$estimate[df$p.value > 0.05] <- NA

table_df <- 
  df %>%
  filter(sampling == "site" | sampling == "individual") %>%
  dplyr::select(contrast, estimate, method, stat, sampling) %>%
  #filter(Variable != "sampstrat") %>%
  spread(contrast, estimate) %>%
  dplyr::select(sampling, method, stat, 
         "EG - G", "EG - R", "EG - T", 
         "G - R", "G - T", 
         "EG - EQ", "EQ - R",
         "R - T") %>%
  mutate(method = factor(method, levels = c("LFMM", "RDA", "MMRR", "GDM")),
         stat = factor(stat, levels = c("TPR relaxed", "TPR strict",
                                  "FDR relaxed", "FDR strict",
                                  "IBD TPR", "IBD FDR", "IBD MAE",
                                  "IBE TPR", "IBE FDR", "IBE MAE"))) %>%
  group_by(sampling) %>%
  group_split() 

table_df_ind <-
  table_df[[1]] %>% dplyr::select(-"EG - EQ",-"EQ - R", -"sampling")
table_df_site <-
  table_df[[2]] %>% dplyr::select(-"EG - G",-"G - R",-"G - T",-"R - T",-"EG - T", -"sampling")

table_df <- left_join(table_df_ind, table_df_site, by = c("stat", "method"))
  
write.csv(table_df, here("p4_analysis", "tukey.csv"), row.names = FALSE)

```

```{r}
big_table_A <- 
  table_df %>%
  pivot_longer(-c("method", "stat")) %>%
  separate_wider_delim(name, " - ", names = c("V1", "V2"))

big_table_B <-
  big_table_A %>%
  mutate(value = -1 * value) %>%
  rename(V1 = V2, V2 = V1)
  
big_table <- 
  bind_rows(big_table_A, big_table_B) %>%
  mutate(name = paste0(V1, " - ", V2)) %>%
  select(-V1, -V2) %>%
  mutate(value = case_when(grepl("TPR", stat) & value > 0 ~ "better",
                   grepl("TPR", stat) & value < 0 ~ "worse",
                   (grepl("FDR", stat) | grepl("MAE", stat)) & value > 0 ~ "worse",
                   (grepl("FDR", stat) | grepl("MAE", stat)) & value < 0 ~ "better",
                   is.na(value) ~ "same",
                   .default = NA)) %>%
  mutate(sampling = case_when((grepl(".y", name) | grepl("EQ", name)) ~ "site", TRUE ~ "individual")) %>%
  arrange(method, stat, name)

big_table_ind <- 
  big_table %>%
  filter(sampling == "individual") %>%
  select(-sampling) %>%
  pivot_wider(names_from = name, values_from = value)

big_table_site <- 
  big_table %>%
  filter(sampling == "site") %>%
  select(-sampling) %>%
  pivot_wider(names_from = name, values_from = value)

big_table_combo <- left_join(big_table_ind, big_table_site)

write.csv(big_table_combo, here("p4_analysis", "tukey_bin.csv"), row.names = FALSE)
```

```{r}
big_table2 <- 
  bind_rows(big_table_A, big_table_B) %>%
  mutate(name = paste0(V1, " - ", V2)) %>%
  select(-V1, -V2) %>%
  mutate(sampling = case_when((grepl(".y", name) | grepl("EQ", name)) ~ "site", TRUE ~ "individual")) %>%
  arrange(method, stat, name)

big_table_ind2 <- 
  big_table2 %>%
  filter(sampling == "individual") %>%
  select(-sampling) %>%
  pivot_wider(names_from = name, values_from = value)

big_table_site2 <- 
  big_table2 %>%
  filter(sampling == "site") %>%
  select(-sampling) %>%
  pivot_wider(names_from = name, values_from = value)

big_table_combo2 <- left_join(big_table_ind2, big_table_site2)

write.csv(big_table_combo2, here("p4_analysis", "tukey_val.csv"), row.names = FALSE)
```

```{r}

big_table_combo %>%
  gt(
    rowname_col = "stat",
    groupname_col = "method"
    ) %>%
  row_group_order(
    groups = c("LFMM", "RDA", "MMRR", "GDM")
    ) %>%
  cols_label(
      method = "Method",
      stat = "Statistic"
    ) %>%
  cols_width(
    c(3:20) ~ px(70),
    c(1)  ~ px(100)
  ) %>%
  cols_label(
    ends_with("G") ~ "G",
    ends_with("EG") ~ "EG",
    ends_with("R") ~ "R",
    ends_with("R.x") ~ "R",
    ends_with("R.y") ~ "R",
    ends_with("T") ~ "T",
    ends_with("EQ") ~ "EQ"
  ) %>%
  data_color(
    c(3:20),
    palette = c("lightgreen", "gray", "tomato")
  ) %>%
  tab_spanner(
    label = "EG",
    columns = c(2:5)
  ) %>% 
  tab_spanner(
    label = "G",
    columns = c(6:8)
  ) %>% 
  tab_spanner(
    label = "R",
    columns = c(9:11)
  ) %>% 
   tab_spanner(
    label = "T",
    columns = c(12:14)
  ) %>%
  tab_spanner(
    label = "Individual-based sampling",
    columns = c(2:14)
  ) %>%
  tab_spanner(
    label = "EG ",
    columns = c(15:16)
  ) %>%
  tab_spanner(
    label = "EQ ",
    columns = c(17:18)
  ) %>%
  tab_spanner(
    label = "R ",
    columns = c(19:20)
  ) %>%
  tab_spanner(
    label = "Site-based sampling",
    columns = c(15:20)
  ) %>%
  tab_style(
    style = list(
      cell_text(color = rgb(0,0,0,0))
      ),
    locations = cells_body(
      columns = c(1:20)
    )
  ) 


```


```{r}
table_df %>%
  gt(
    rowname_col = "stat",
    groupname_col = "method"
    ) %>%
  row_group_order(
    groups = c("LFMM", "RDA", "MMRR", "GDM")
    ) %>%
  cols_label(
      method = "Method",
      stat = "Statistic"
    ) %>% 
  fmt_number(
    columns = c(3:11),
    decimals = 3,
    suffixing = TRUE
    ) %>%
  gtExtras::gt_hulk_col_numeric(
    c(3:11), 
    trim = TRUE, 
    domain = c(-0.18,0.18),
    na.color = "white"
    ) %>%
  sub_missing(
    columns = everything(),
    rows = everything(),
    missing_text = "n.s."
    ) %>%
  cols_width(
    c(3:11) ~ px(70)
  ) %>%
  cols_label(
    `EG - R.x` = "EG - R",
    `EG - R.y` = "EG - R"
  ) %>%
  tab_spanner(
    label = "Individual-based sampling",
    columns = c(1:8)
  ) %>%
  tab_spanner(
    label = "Site-based sampling",
    columns = c(9:11)
  )

```

```{r}

compare_numbers <- function(vec) {
  if (length(vec) != 4) {
    stop("Input vector must contain exactly four elements.")
  }
  
  comparison <- map_chr(1:3, ~ {
    x <- vec[.x]
    print(x)
    y <- vec[.x + 1]
    if (x > y) {
      paste(x, ">", y)
    } else if (x < y) {
      paste(x, "<", y)
    } else {
      paste(x, "=", y)
    }
  })
  
  result <- paste(comparison, collapse = " ")
  return(result)
}

# Example usage
numbers <- c(2, 4, 2, 2)
result <- compare_numbers(numbers)
cat("Comparison:", result)

lfmm_ind %>% 
  group_by(K, phi, m, H, r, sampstrat) %>% 
  summarize(mean = mean(TPRCOMBO_allFALSE, na.rm = TRUE)) %>% 
  group_by(K, phi, m, H, r) %>% 
  filter(mean == max(mean)) %>%
  group_by(sampstrat) %>%
  summarize(count = n())

lfmm_ind %>% 
  group_by(K, phi, m, H, r, sampstrat) %>% 
  summarize(mean = mean(TPRCOMBO_allFALSE, na.rm = TRUE)) %>% 
  group_by(K, phi, m, H, r) %>% 
  filter(mean == min(mean)) %>%
  group_by(sampstrat) %>%
  summarize(count = n())

lfmm_site %>% 
  group_by(K, phi, m, H, r, sampstrat) %>% 
  summarize(mean = mean(TPRCOMBO_allFALSE, na.rm = TRUE)) %>% 
  group_by(K, phi, m, H, r) %>% 
  filter(mean == min(mean)) %>%
  group_by(sampstrat) %>%
  summarize(count = n())


lfmm_site %>% 
  group_by(K, phi, m, H, r, sampstrat, nsamp) %>% 
  summarize(mean = mean(TPRCOMBO_allFALSE, na.rm = TRUE)) %>% 
  group_by(K, phi, m, H, r) %>% 
  filter(mean == max(mean)) %>%
  group_by(sampstrat) %>%
  summarize(count = n())

```

