---
title: "example_simulations"
output: html_document
date: "2022-09-27"
---
```{r}
library("raster")
library("here")
library("tidyverse")
library("viridis")
library("gridExtra")

source(here("general_functions.R"))
```


```{r, fig.height = 8, fig.width = 4}
env1 <- raster(as.matrix(read.csv(here("p4_analysis/example_data/seed1_env1_H50_r60.csv"), header = FALSE)))
env2 <- raster(as.matrix(read.csv(here("p4_analysis/example_data/seed1_env2_H50_r60.csv"), header = FALSE)))
extent(env1) <- c(0,100,-100,0)
extent(env2) <- c(0,100,-100,0)
envstk <- stack(env1, env2)
env1 <- data.frame(raster::rasterToPoints(env1), env = 1)
env2 <- data.frame(raster::rasterToPoints(env2), env = 2)
env <- rbind(env1, env2)

envpc <- RStoolbox::rasterPCA(envstk)
envpc <- envpc$map[[1]]
envpcdf <- data.frame(rasterToPoints(envpc))

p1 <- ggplot(env1) +
  geom_tile(aes(x = x, y = y, fill = layer)) +
  coord_equal() +
  theme_void() + 
  scale_fill_viridis(option = "mako") + 
  facet_wrap(~ env, ncol = 1) + 
  theme(legend.position = "none", strip.text.x = element_blank())

p2 <- ggplot(env2) +
  geom_tile(aes(x = x, y = y, fill = layer)) +
  coord_equal() +
  theme_void() + 
  scale_fill_viridis(option = "mako") + 
  facet_wrap(~ env, ncol = 1) + 
  theme(legend.position = "none", strip.text.x = element_blank())

grid.arrange(p1, p2, ncol = 1)

```

```{r, fig.width=4, fig.height=8}
df <- get_gsd(here("p4_analysis/example_data/mod-K2_phi50_m100_seed1_H50_r60_it-0_t-1000_spp-spp_0.csv"))

p1 <- ggplot() +
  geom_tile(data = env1, aes(x = x, y = y, fill = layer), alpha = 0.5) +
  geom_point(data = df, aes(x, y, fill = z1), colour = rgb(1,1,1,0.5), pch = 21, size = 2) +
  coord_equal() +
  theme_void() + 
  scale_color_viridis(option = "mako") + 
  scale_fill_viridis(option = "mako") +
  theme(legend.position = "none")

p2 <- ggplot() +
  geom_tile(data = env1, aes(x = x, y = y, fill = layer), alpha = 0.5) +
  geom_point(data = df, aes(x, y, fill = z2), colour = rgb(1,1,1,0.5), pch = 21, size = 2) +
  coord_equal() +
  theme_void() + 
  scale_color_viridis(option = "mako") + 
  scale_fill_viridis(option = "mako") +
  theme(legend.position = "none")

grid.arrange(p1, p2, ncol = 1)
```
```{r, fig.width=4, fig.height=8}

subdf <- df[sample(nrow(df), 144), ]
p1 <- ggplot() +
  geom_tile(data = env1, aes(x = x, y = y, fill = layer), alpha = 0.5) +
  geom_point(data = subdf, aes(x, y, fill = z1), colour =rgb(0,0,0,0.5), pch = 21, size = 3) +
  coord_equal() +
  theme_void() + 
  scale_color_viridis(option = "mako") + 
  scale_fill_viridis(option = "mako") +
  theme(legend.position = "none")

p2 <- ggplot() +
  geom_tile(data = env1, aes(x = x, y = y, fill = layer), alpha = 0.5) +
  geom_point(data = subdf, aes(x, y, fill = z2), colour = rgb(0,0,0,0.5), pch = 21, size = 3) +
  coord_equal() +
  theme_void() + 
  scale_color_viridis(option = "mako") + 
  scale_fill_viridis(option = "mako") +
  theme(legend.position = "none")

grid.arrange(p1, p2, ncol = 1)
```


```{r}
vcf <- vcfR::read.vcfR(here("p4_analysis/example_data/mod-K2_phi50_m100_seed1_H50_r60_it-0_t-1000_spp-spp_0.vcf"))
dos <- vcf_to_dosage(vcf)
colnames(dos) <- paste0("locus_", 1:ncol(dos))
df <- data.frame(df, dos)

```

```{r, fig.width = 4, fig.height = 9}

ggplot(dfs[dfs$wdim == 0,], aes(x = env1, y = custom)) + 
  #geom_hex(bins = 20) +
  geom_point(alpha = 0.4) +
  stat_smooth(method = "glm", se = TRUE) +
  facet_grid(locus~wdim) + 
  scale_fill_viridis_c(option = "plasma", end = 0.9) 
```


```{r, fig.width = 16, fig.height = 8}

gd <- 
  df %>%
  pivot_longer(paste0("locus_", 1:8), names_to = "locus") %>%
  mutate(locus = gsub("locus_", "", locus)) %>%
  mutate(value = value/2)

gd1 <- gd %>% filter(locus %in% c(1,2,3,4))

p1 <- ggplot() +
  geom_tile(data = env1, aes(x = x, y = y, fill = layer), alpha = 0.5) +
  geom_point(data = gd1, aes(x, y, col = value), size = 4) +
  coord_equal() +
  theme_void() + 
  scale_fill_viridis(option = "mako") +
  scale_color_viridis(option = "magma") +
  theme(legend.position = "none", strip.text.x = element_blank()) +
  facet_grid( ~ locus)


gd2 <- gd %>% filter(locus %in% c(5,6,7,8))

p2 <- ggplot() +
  geom_tile(data = env2, aes(x = x, y = y, fill = layer), alpha = 0.5) +
  geom_point(data = gd2, aes(x, y, col = value), size = 4) +
  coord_equal() +
  theme_void() + 
  scale_fill_viridis(option = "mako") +
  scale_color_viridis(option = "magma") +
  theme(legend.position = "none", strip.text.x = element_blank()) +
  facet_grid( ~ locus)


grid.arrange(p1, p2, nrow = 2)
```


```{r, fig.width = 8, fig.height=8}
set.seed(144)
s <- sample(nrow(dos), 144)
gendist <- as.matrix(dist(dos[s,], diag = TRUE, upper = TRUE))
p1 <- gendist  %>%
  data.frame() %>%
  rownames_to_column("sample") %>%
  gather("sample2", "gendist", -"sample") %>%
  ggplot(ggplot2::aes(x = sample, y = sample2, fill = gendist)) +
    geom_tile() +
    coord_equal() +
    scale_fill_viridis(option = "mako") +
    theme_void() +
    theme(legend.position = "none", plot.margin = unit(rep(0.5,4), "cm")) 

envdist1 <- as.matrix(dist(df$env1[s], diag = TRUE, upper = TRUE))
p2 <- envdist1  %>%
  data.frame() %>%
  rownames_to_column("sample") %>%
  gather("sample2", "gendist", -"sample") %>%
  ggplot(ggplot2::aes(x = sample, y = sample2, fill = gendist)) +
    geom_tile() +
    coord_equal() +
    scale_fill_viridis(option = "viridis") +
    theme_void() +
    theme(legend.position = "none", plot.margin = unit(rep(0.5,4), "cm")) 

envdist2 <- as.matrix(dist(df$env2[s], diag = TRUE, upper = TRUE))
p3 <- envdist2 %>%
  data.frame() %>%
  rownames_to_column("sample") %>%
  gather("sample2", "gendist", -"sample") %>%
  ggplot(ggplot2::aes(x = sample, y = sample2, fill = gendist)) +
    geom_tile() +
    coord_equal() +
    scale_fill_viridis(option = "viridis") +
    theme_void() +
    theme(legend.position = "none", plot.margin = unit(rep(0.5,4), "cm")) 

geodist <- as.matrix(dist(df[s,c("x","y")], diag = TRUE, upper = TRUE))
p4 <- geodist %>%
  data.frame() %>%
  rownames_to_column("sample") %>%
  gather("sample2", "gendist", -"sample") %>%
  ggplot(ggplot2::aes(x = sample, y = sample2, fill = gendist)) +
    geom_tile() +
    coord_equal() +
    scale_fill_viridis(option = "viridis") +
    theme_void() +
    theme(legend.position = "none", plot.margin = unit(rep(0.5,4), "cm")) 

grid.arrange(p1,p2,p3,p4,nrow = 2)

p1
```

```{r, include = false}

plot_phenotype2 <- function(df1, df2, env, title1){
  df1$y <- -df1$y
  df2$y <- -df2$y
  
  p1 <- ggplot() +
    geom_tile(data = env, aes(x = x, y = y), fill = "gray", alpha = 0.5) +
    geom_point(data = df1, aes(x, y, col = z1), size = 0.9, alpha = 0.7) +
    coord_equal() +
    theme_void() + 
    scale_color_viridis(option = "viridis", limits = c(0,1)) + 
    theme(legend.position = "none")
  
  p2 <- ggplot() +
    geom_tile(data = env, aes(x = x, y = y), fill = "gray", alpha = 0.5) +
    geom_point(data = df2, aes(x, y, col = z1), size = 0.9, alpha = 0.7) +
    coord_equal() +
    theme_void() + 
    scale_color_viridis(option = "viridis", limits = c(0,1)) + 
    theme(legend.position = "none")
  
  plt <- grid.arrange(p1, p2, nrow = 2)
  plt <- grid.arrange(plt, top = grid::textGrob(title1, just = "center", gp=gpar(fontsize=20)))
}

new_cols <- function(x, level, param){
  x$level <- level
  x$param <- param
  return(x)
}

dfs <- purrr::map(list.files(here("p4_analysis/example_data/example_combos"), full.names = TRUE), get_gsd)
names(dfs) <- c("phi10", "H5", "r30", "D", "m25", "K2")

df <- bind_rows(new_cols(dfs[["phi10"]], "low", "selection\nstrength"),
          new_cols(dfs[["D"]], "high", "selection\nstrength"),
          new_cols(dfs[["H5"]], "low", "spatial\nautocorrelation"),
          new_cols(dfs[["D"]], "high", "spatial\nautocorrelation"),
          new_cols(dfs[["r30"]], "low", "environmental\ncorrelation"),
          new_cols(dfs[["D"]], "high", "environmental\ncorrelation"),
          new_cols(dfs[["D"]], "low", "population size"),
          new_cols(dfs[["K2"]], "high", "population size"),
          new_cols(dfs[["m25"]], "low", "migration"),
          new_cols(dfs[["D"]], "high", "migration")) %>%
  mutate(param = factor(param, 
                        levels = c("population size", "migration", "selection\nstrength", 
                        "spatial\nautocorrelation", "environmental\ncorrelation"))) %>%
  mutate(level = factor(level, levels = c("low", "high")))

```

```{r, fig.width = 18, fig.height= 9}
df1 <- data.frame(df, zw = df$z1, 
                  xw = scales::rescale(df$x, to=c(0,0.48)), yw = scales::rescale(df$y, to=c(0,0.48)))
df2 <- data.frame(df, zw = df$z2, 
                  xw = scales::rescale(df$x, to=c(0.52,1)), yw = scales::rescale(df$y, to=c(0,0.48)))
dfw <- bind_rows(df1, df2)

```

```{r, fig.height = 12, fig.width= 10}

ggplot(dfw, aes(x = xw, y = yw, col = zw)) + 
  geom_rect(xmin = 0, xmax = 0.48, ymin = 0, ymax = 0.48, fill = "#D3D3D3", col = "#D3D3D3") +
  geom_rect(xmin = 0.52, xmax = 1, ymin = 0, ymax = 0.48, fill = "#D3D3D3", col = "#D3D3D3") +
  geom_point(pch = 16, size = 0.9) +
  geom_rect(xmin = 0, xmax = 0.10, ymin = 0.42, ymax = 0.48, 
            fill = "white", col = "white", lwd = 2, alpha = 0.2) +
  geom_rect(xmin = 0.52, xmax = 0.62, ymin = 0.42, ymax = 0.48,
            fill = "white", col = "white", lwd = 2, alpha = 0.2) +
  annotate("text", x = 0.05, y = 0.45, label = "T1", col = "darkgray", size = 6) +
  annotate("text", x = 0.57, y = 0.45, label = "T2", col = "darkgray", size = 6) +
  facet_grid(param ~ level, switch = "both") +
  theme_bw() +
  scale_color_viridis_c(option = "mako", alpha = 0.8)+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), legend.position = "none",
        axis.title.x=element_blank(), axis.ticks.x=element_blank(),
        axis.title.y=element_blank(), axis.ticks.y=element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(), 
        plot.margin=unit(rep(0.4,4),"cm"),
        strip.text.x = element_text(size = 20),
        strip.text.y = element_text(size = 20),
        strip.background =element_blank(),
        strip.text = element_text(color = "#282828"),
        plot.title = element_text(size=20),
        legend.key.size = unit(1, 'cm'), 
        panel.border = element_rect(colour = "gray", fill = NA, linewidth = 1)) +
  coord_fixed() 

```



```{r}
get_samples <- function(param_set, sampstrat, nsamp, site = FALSE){
  #param_set - vector of one set of parameters (e.g. params[i,])
  #sampstrat - sampling strategy (e.g. "rand", "grid", "trans", "envgeo")
  #nsamp - number of samples

  if(!site) subIDs <- read.csv(here("p4_analysis/example_data/samples", paste0("/samples_", sampstrat, nsamp, ".csv")))
  if(site) subIDs <- read.csv(here("p4_analysis/example_data/samples", paste0("/site_samples_", sampstrat, nsamp, ".csv")))
  
  subIDs <- subIDs[subIDs$K == param_set$K 
                   & subIDs$phi == param_set$phi
                   & subIDs$m == param_set$m 
                   & subIDs$seed == param_set$seed
                   & subIDs$H == param_set$H
                   & subIDs$r == param_set$r
                   & subIDs$it == param_set$it,]
  
  #confirm there is only one set of IDs being used
  stopifnot(nrow(subIDs) == 1)
  
  #remove parameter columns and convert to vector of IDs
  subIDs <- subIDs[,!names(subIDs) %in% names(param_set)]
  subIDs <- unlist(subIDs)
  
  #confirm that final set of IDs is a vector
  stopifnot(is.vector(subIDs))
  
  return(as.character(subIDs))
}
```

```{r}

plot_samples <- function(.x, .y, site = FALSE, df, env1){
  #subsample from data based on sampling strategy and number of samples
  if (site) subIDs <- get_samples(param_set, sampstrat = .x, nsamp = 16, site = TRUE)
  if (!site) subIDs <- get_samples(param_set, sampstrat = .x, nsamp = 81, site = FALSE)
  subgsd_df <- df[subIDs,]
  
  p <- ggplot() +
    geom_tile(data = env1, aes(x = x, y = y, fill = layer), alpha = 0.5) +
    geom_point(data = subgsd_df, aes(x, y, fill = z1), 
               colour = rgb(0,0,0,0.5), pch = 21, size = 3) +
    coord_equal() +
    theme_void() + 
    scale_color_viridis(option = "mako") + 
    scale_fill_viridis(option = "mako") +
    theme(legend.position = "none", plot.title = element_text(hjust = 0.5, size = 20)) +
    ggtitle(.y)
  
  return(p)
}

df <- get_gsd(here("p4_analysis/example_data/example_combos/mod-K1_phi100_m100_seed1_H50_r60_it-0_t-1000_spp-spp_0.csv"))

param_set <- data.frame(K = 1, phi = 1, m = 1, seed = 1, H = 0.50, r = 0.60, it = 0)

grd_site <- map2(c("rand", "equi", "envgeo"), c("R", "EQ", "EG"), 
                 plot_samples, site = TRUE, env1 = env1, df = df)

grd_ind <- map2(c("rand", "grid", "envgeo", "trans"), 
               c("R", "G", "EG", "T"), plot_samples, site = FALSE, env1 = env1, df = df)

site0 <- do.call(grid.arrange, c(grd_site, nrow = 1, ncol = 4))
site <- grid.arrange(site0, 
                    left = grid::textGrob("site", 
                                          x = 0, 
                                          hjust = 0.9, 
                                          vjust = 1,
                                          rot = 90,
                                          gp=gpar(fontsize=20)))

ind0 <- do.call(grid.arrange, c(grd_ind, nrow = 1))
ind <- grid.arrange(ind0, 
                    left = grid::textGrob("individual", 
                                          x = 0, 
                                          hjust = 0.6, 
                                          vjust = 1,
                                          rot = 90,
                                          gp=gpar(fontsize=20)))

```
```{r, fig.height = 7, fig.width = 11}
grid.arrange(ind,site)
```




# IGNORE
```{r}
library(algatr)
vcf1 <- vcfR::read.vcfR(here("p4_analysis/example_data/mod-K2_phi50_m100_seed1_H50_r60_it-0_t-1000_spp-spp_0.vcf"))
df1 <- get_gsd(here("p4_analysis/example_data/mod-K2_phi50_m100_seed1_H50_r60_it-0_t-1000_spp-spp_0.csv"))
df1$y <- -df1$y
s <- sample(nrow(df1), 36)

env1 <- raster(as.matrix(read.csv(here("p4_analysis/example_data/seed1_env1_H50_r60.csv"), header = FALSE)))
env2 <- raster(as.matrix(read.csv(here("p4_analysis/example_data/seed1_env2_H50_r60.csv"), header = FALSE)))
extent(env1) <- c(0,100,-100,0)
extent(env2) <- c(0,100,-100,0)
envstk <- stack(env1, env2)

gen1 <- vcf_to_dosage(vcf1[,c(1, s + 1)])
gen1f <- vcf_to_dosage(vcf1[,c(1, 1:200 + 1)])

Ktw <- select_K_tw(gen1, criticalpoint = 2.0234) 

Kscree <- select_K_elbow(gen1, low = 0.08, max.pc = 0.70) 

Kfc <- select_K_fc(gen1, pca.select = "percVar", perc.pca = 90, max.n.clust = 10)

Ktess <- select_K_tess(gen1, df1[s,c("x","y")], Kvals = 1:20, tess_method = "projected.ls") 


pc <- prcomp(gen1)
pc <- pc$sdev^2
plot(pc, xlim = c(0,30))
abline(v = Ktw, col = "red", lwd = 4)
abline(v = Kscree, col = "blue", lwd = 3)
abline(v = Kfc, col = "green", lwd = 2)
abline(v = Ktess, col = "purple", lwd = 1)

tess_res <- tess_do_everything(gen1,  df1[s,c("x","y")], grid = envstk[[1]], Kvals = 1:20)
tess_res <- tess_do_everything(gen1,  df1[s,c("x","y")], grid = envstk[[1]], Kvals = 8)


lfmm_res <- lfmm_do_everything(vcf1[,c(1, s + 1)], 
                               coords = df1[s, c("x","y")], 
                               env = envstk, K = 2)

rda_res <- rda_do_everything(vcf1[,c(1, 1:200+ 1)], 
                             coords = df1[1:200, c("x","y")],
                             env = envstk,
                             model = "full")

env <- raster::extract(envstk, df1[1:200, c("x","y")])
rv1 <- rda_varpart(gen1f, env = env, coords = df1[1:200, c("x","y")], Pin = 0.05, R2permutations = 100, R2scope = T, nPC = 3)
rda_varpart_table(rv1)
```


```{r}
library(algatr)
vcf2 <- vcfR::read.vcfR(here("p4_analysis/example_data/mod-K1_phi50_m25_seed1_H50_r60_it-0_t-1000_spp-spp_0.vcf"))
df2 <- get_gsd(here("p4_analysis/example_data/mod-K1_phi50_m25_seed1_H50_r60_it-0_t-1000_spp-spp_0.csv"))
df2$y <- -df2$y
s <- sample(nrow(df2), 36)

gen2 <- vcf_to_dosage(vcf2[,c(1, s + 1)])
gen2f <- vcf_to_dosage(vcf2[,c(1, 1:200 + 1)])

Ktw <- select_K_tw(gen2, criticalpoint = 2.0234) 

Kscree <- select_K_elbow(gen2, low = 0.08, max.pc = 0.70) 

Kfc <- select_K_fc(gen2, pca.select = "percVar", perc.pca = 90, max.n.clust = 10)

Ktess <- select_K_tess(gen2, df2[s,c("x","y")], Kvals = 1:20, tess_method = "projected.ls") 


pc <- prcomp(gen2)
pc <- pc$sdev^2
plot(pc, xlim = c(0,30))
abline(v = Ktw, col = "red", lwd = 4)
abline(v = Kscree, col = "blue", lwd = 3)
abline(v = Kfc, col = "green", lwd = 2)
abline(v = Ktess, col = "purple", lwd = 1)

tess_res <- tess_do_everything(gen2,  df2[s,c("x","y")], grid = envstk[[1]], Kvals = 1:20)
tess_res <- tess_do_everything(gen2,  df2[s,c("x","y")], grid = envstk[[1]], Kvals = 4)


lfmm_res <- lfmm_do_everything(vcf2[,c(1, s + 1)], 
                               coords = df2[s, c("x","y")], 
                               env = envstk, K = 2)

rda_res <- rda_do_everything(vcf2[,c(1, 1:200+ 1)], 
                             coords = df2[1:200, c("x","y")],
                             env = envstk,
                             model = "full")

env <- raster::extract(envstk, df2[1:200, c("x","y")])
rv2 <- rda_varpart(gen2f, env = env, coords = df2[1:200, c("x","y")], Pin = 0.05, R2permutations = 100, R2scope = T, nPC = 3)

rda_varpart_table(rv2)
```

```{r}
# Convert to genlight
genind1 <- vcfR::vcfR2genind(vcf1[,1:201])
#test <- adegenet::fstat(genind1, pop=1:200, )
test <- fst.dosage(gen1[1:4,], pop = c(1, 2))
```
```{r}
# Create a blank raster with 100 rows and 100 columns
r <- raster(nrow = 10, ncol = 10)
y <- init(r, fun=1:ncell(r))
extent(y) <- extent(0, 100, -100, 0)

pop <- extract(y, df1[1:200, c("x", "y")])
ggplot(data = df1[1:200,], aes(x = x, y = y, col = pop)) + geom_point() + coord_equal()
test1 <- fst.dosage(gen1f[1:200,], pop = pop)
test1["All"]

pop <- extract(y, df2[1:200, c("x", "y")])
ggplot(data = df2[1:200,], aes(x = x, y = y, col = pop)) + geom_point() + coord_equal()
test2 <- fst.dosage(gen2f[1:200,], pop = pop)
test2["All"]
```
```{r, fig.width = 21, fig.height = 13}
cline <- read.csv(here("p3_methods/outputs/cline_results.csv"))
cline <- cline %>% mutate_at(c("K", "phi", "m", "seed", "H", "r", "it", "nsamp", "sampstrat"), as.factor)

MEGAPLOT(cline, stat = "cor", colpal = "plasma")

MEGAPLOT(cline, stat = "prop", colpal = "plasma")
```
