---
title: "debug"
output: html_document
---

```{r}
df <- do.call(rbind, lapply(list.files(path = "/Users/Anusha/Documents/GitHub/LandGenSamp/p3_methods/outputs/GDM/temp/", full.names = TRUE), read.csv))
df[,colnames(params_full)] <- data.frame(lapply(df[,colnames(params_full)], as.factor))
```

```{r}
df2<- read.csv("/Users/Anusha/Documents/GitHub/LandGenSamp/p3_methods/outputs/GDM/gdm_results.csv")
df2[,colnames(params_full)] <- data.frame(lapply(df[,colnames(params_full)], as.factor))
```

```{r}
t <- c(colnames(params_full), "geo_coeff")
test <- merge(df[,t], df2[,t], by = colnames(params_full))

plot(test$geo_coeff.x, test$geo_coeff.y)

table(test$geo_coeff.x[order(test$geo_coeff.x)] == test$geo_coeff.y[order(test$geo_coeff.y)])

testdf <- cbind(test$geo_coeff.y, test$geo_coeff.x)
head(testdf)
tail(testdf)
```

```{r}
params_full
```

```{r}

summary_hplot <- function(df, colpal = "plasma", full=FALSE){
  
  if(!full){sampstratsub <- sampstrat[-which(sampstrat=="full")]}
  if(!full){nsampsub <- nsamp[-which(nsamp==2000)]}
  
  resdf <- data.frame()
  
  for(n in nsampsub){
    for(s in sampstratsub){
      subdf <- df[df$sampstrat == s & df$nsamp == n, ]
      
      meandf <- data.frame()
      for(p in c("K", "m", "phi", "H", "r")){
        aggdf <- aggregate(subdf$stat, list(subdf[,p]), mean)
        aggdf[,1] <- paste(p,"=", aggdf[,1])
        aggdf$param <- p
        meandf <- rbind.data.frame(meandf, aggdf)
      }
      
      colnames(meandf) <- c("group", "mean", "param")
      
      #save results
      tempdf <- data.frame(meandf)
      tempdf$nsamp <- n
      tempdf$sampstrat <- s
      resdf <- rbind.data.frame(resdf, tempdf)
    }
  }
  
  row.names(resdf) <- NULL
  resdf$nsamp <- as.factor(resdf$nsamp)
  
  ## plot data
  plts <- list()
  for(i in 1:length(unique(resdf$group))){
    tempdf <- resdf[resdf$group == unique(resdf$group)[i],]
    p <- ggplot(tempdf, aes(nsamp, sampstrat)) +
      ggtitle(unique(tempdf$group)) +
      geom_tile(aes(fill = mean)) + 
      geom_text(aes(label = round(mean, digits = 2), hjust = 0.5)) +
      scale_fill_viridis(limits=c(min(resdf$mean),max(resdf$mean)), option = colpal) +
      theme_bw() +
      theme(panel.border = element_blank(), panel.grid.major = element_blank(), 
            panel.grid.minor = element_blank(), legend.position = "none",
            axis.title.x=element_blank(), axis.ticks.x=element_blank(),
            axis.title.y=element_blank(), axis.ticks.y=element_blank(),
            axis.text.x = element_text(color = "grey50", size = 14),
            axis.text.y = element_text(color = "gray50", size = 14), 
            plot.margin=unit(rep(0.4,4),"cm")) +
      coord_fixed()
    
    plts[[i]] <- p
  }
  
  
  plts2 <- list()
  o <- 1
  for(i in seq(1, length(plts), 2)){
    plts2[[o]] <- do.call(grid.arrange, c(plts[c(i,i+1)], nrow=2))
    o <- o+1
  }
  
  plt <- do.call(grid.arrange, c(plts2, nrow=1))
  return(plt)
}

```

