---
title: "fitness_test"
output: html_document
---


```{r}
library(here)
```

```{r}
plot(1,1,col="white", ylim=c(0,0.04), xlim=c(0,600), xlab="t", ylab="mean(|z - env|*phi)")
for(i in seq(0,600,100)){
  #read in geospatial data
  file_path = here("data",paste0("mod-10k_K2_phi50_m25_seed1_H50_r60_it--1_t-",i,"_spp-spp_0.csv"))
  gsd_df <- read.csv(file_path)
  gsd_df$env1 <- as.numeric(stringr::str_extract(gsd_df$e, '(?<=, )[^,]+(?=,)')) 
  gsd_df$env2 <- as.numeric(stringr::str_extract(gsd_df$e, '(?<=, )[^,]+(?=\\])')) 
  gsd_df$z1 <- as.numeric(stringr::str_extract(gsd_df$z, '(?<=\\[)[^,]+(?=,)'))
  gsd_df$z2 <- as.numeric(stringr::str_extract(gsd_df$z, '(?<=, )[^,]+(?=\\])')) 
  
  points(i, mean(abs(gsd_df$z1 - gsd_df$env1)*0.1), pch = 1, col = "black")
  points(i, mean(abs(gsd_df$z2 - gsd_df$env2)*0.1), pch = 19, col = "black")
  
  #read in geospatial data
  file_path = here("data",paste0("mod-10k_K2_phi50_m100_seed1_H50_r60_it--1_t-",i,"_spp-spp_0.csv"))
  gsd_df <- read.csv(file_path)
  gsd_df$env1 <- as.numeric(stringr::str_extract(gsd_df$e, '(?<=, )[^,]+(?=,)')) 
  gsd_df$env2 <- as.numeric(stringr::str_extract(gsd_df$e, '(?<=, )[^,]+(?=\\])')) 
  gsd_df$z1 <- as.numeric(stringr::str_extract(gsd_df$z, '(?<=\\[)[^,]+(?=,)'))
  gsd_df$z2 <- as.numeric(stringr::str_extract(gsd_df$z, '(?<=, )[^,]+(?=\\])')) 
  
  points(i, mean(abs(gsd_df$z1 - gsd_df$env1)*0.1), pch = 1, col = "blue")
  points(i, mean(abs(gsd_df$z2 - gsd_df$env2)*0.1), pch = 19, col = "blue")
  
}

legend("bottomleft", pch = c(19,19), col=c("black","blue"), c("m = 0.25", "m = 1"))

plot(1,1,col="white", ylim=c(0,3000), xlim=c(0,600), xlab="t", ylab="pop size")
for(i in seq(0,600,100)){
  #read in geospatial data
  file_path = here("data",paste0("mod-10k_K2_phi50_m25_seed1_H50_r60_it--1_t-",i,"_spp-spp_0.csv"))
  gsd_df <- read.csv(file_path)
  
  points(i, nrow(gsd_df), pch = 19, col = "black")
  
  file_path = here("data",paste0("mod-10k_K2_phi50_m100_seed1_H50_r60_it--1_t-",i,"_spp-spp_0.csv"))
  gsd_df <- read.csv(file_path)
  
  points(i, nrow(gsd_df), pch = 19, col = "blue")
}

legend("bottomleft", pch = c(19,19), col=c("black","blue"), c("m = 0.25", "m = 1"))

```

```{r}
plot(1,1,col="white", ylim=c(0,0.04), xlim=c(0,1000), xlab="t", ylab="mean(|z - env|*phi)")
for(i in seq(0,1000,100)){
  #read in geospatial data
  file_path = here("data",paste0("mod-10k_K1_phi10_m50_seed1_H50_r60_it--1_t-",i,"_spp-spp_0.csv"))
  gsd_df <- read.csv(file_path)
  gsd_df$env1 <- as.numeric(stringr::str_extract(gsd_df$e, '(?<=, )[^,]+(?=,)')) 
  gsd_df$env2 <- as.numeric(stringr::str_extract(gsd_df$e, '(?<=, )[^,]+(?=\\])')) 
  gsd_df$z1 <- as.numeric(stringr::str_extract(gsd_df$z, '(?<=\\[)[^,]+(?=,)'))
  gsd_df$z2 <- as.numeric(stringr::str_extract(gsd_df$z, '(?<=, )[^,]+(?=\\])')) 
  
  points(i, mean(abs(gsd_df$z1 - gsd_df$env1)*0.1), pch = 19, col = "black")
  points(i, mean(abs(gsd_df$z2 - gsd_df$env2)*0.1), pch = 19, col = "blue")
}


```


```{r}
plot(1,1,col="white", ylim=c(0,0.04), xlim=c(0,1000), xlab="t", ylab="mean(|z - env|*phi)")
for(i in seq(0,1000,100)){
  #read in geospatial data
  file_path = here("data",paste0("mod-10k_K1_phi10_m25_seed1_H50_r60_it--1_t-",i,"_spp-spp_0.csv"))
  gsd_df <- read.csv(file_path)
  gsd_df$env1 <- as.numeric(stringr::str_extract(gsd_df$e, '(?<=, )[^,]+(?=,)')) 
  gsd_df$env2 <- as.numeric(stringr::str_extract(gsd_df$e, '(?<=, )[^,]+(?=\\])')) 
  gsd_df$z1 <- as.numeric(stringr::str_extract(gsd_df$z, '(?<=\\[)[^,]+(?=,)'))
  gsd_df$z2 <- as.numeric(stringr::str_extract(gsd_df$z, '(?<=, )[^,]+(?=\\])')) 
  
  points(i, mean(abs(gsd_df$z1 - gsd_df$env1)*0.1), pch = 1, col = rgb(1,0,1,0.6))
  points(i, mean(abs(gsd_df$z2 - gsd_df$env2)*0.1), pch = 19, col = rgb(1,0,1,0.6))
  
  #read in geospatial data
  file_path = here("data",paste0("mod-10k_K1_phi10_m50_seed1_H50_r60_it--1_t-",i,"_spp-spp_0.csv"))
  gsd_df <- read.csv(file_path)
  gsd_df$env1 <- as.numeric(stringr::str_extract(gsd_df$e, '(?<=, )[^,]+(?=,)')) 
  gsd_df$env2 <- as.numeric(stringr::str_extract(gsd_df$e, '(?<=, )[^,]+(?=\\])')) 
  gsd_df$z1 <- as.numeric(stringr::str_extract(gsd_df$z, '(?<=\\[)[^,]+(?=,)'))
  gsd_df$z2 <- as.numeric(stringr::str_extract(gsd_df$z, '(?<=, )[^,]+(?=\\])')) 
  
  points(i, mean(abs(gsd_df$z1 - gsd_df$env1)*0.1), pch = 1, col = rgb(0,1,1,0.6))
  points(i, mean(abs(gsd_df$z2 - gsd_df$env2)*0.1), pch = 19, col = rgb(0,1,1,0.6))
  
  #read in geospatial data
  file_path = here("data",paste0("mod-10k_K1_phi10_m1_seed1_H50_r60_it--1_t-",i,"_spp-spp_0.csv"))
  gsd_df <- read.csv(file_path)
  gsd_df$env1 <- as.numeric(stringr::str_extract(gsd_df$e, '(?<=, )[^,]+(?=,)')) 
  gsd_df$env2 <- as.numeric(stringr::str_extract(gsd_df$e, '(?<=, )[^,]+(?=\\])')) 
  gsd_df$z1 <- as.numeric(stringr::str_extract(gsd_df$z, '(?<=\\[)[^,]+(?=,)'))
  gsd_df$z2 <- as.numeric(stringr::str_extract(gsd_df$z, '(?<=, )[^,]+(?=\\])')) 
  
  points(i, mean(abs(gsd_df$z1 - gsd_df$env1)*0.1), pch = 1, col = rgb(0,0,1,0.6))
  points(i, mean(abs(gsd_df$z2 - gsd_df$env2)*0.1), pch = 19, col = rgb(0,0,1,0.6))
}
legend("topleft", pch = c(1,19), c("trait 1", "trait 2"))
legend("topright", col = c(rgb(1,0,1,0.6),rgb(0,1,1,0.6),rgb(0,0,1,0.6)), pch=19,  c("low m (0.25)", "med m (0.50)", "high m (1.00)"))
```
```{r}
plot(1,1,col="white", ylim=c(0,0.04), xlim=c(0,1000), xlab="t", ylab="mean(|z - env|*phi)")
for(i in seq(0,1000,100)){
  #read in geospatial data
  file_path = here("data",paste0("mod-2l_10k_K1_phi10_m25_seed1_H50_r60_it--1_t-",i,"_spp-spp_0.csv"))
  gsd_df <- read.csv(file_path)
  gsd_df$env1 <- as.numeric(stringr::str_extract(gsd_df$e, '(?<=, )[^,]+(?=,)')) 
  gsd_df$env2 <- as.numeric(stringr::str_extract(gsd_df$e, '(?<=, )[^,]+(?=\\])')) 
  gsd_df$z1 <- as.numeric(stringr::str_extract(gsd_df$z, '(?<=\\[)[^,]+(?=,)'))
  gsd_df$z2 <- as.numeric(stringr::str_extract(gsd_df$z, '(?<=, )[^,]+(?=\\])')) 
  
  points(i, mean(abs(gsd_df$z1 - gsd_df$env1)*0.1), pch = 1, col = rgb(1,0,1,0.6))
  points(i, mean(abs(gsd_df$z2 - gsd_df$env2)*0.1), pch = 19, col = rgb(1,0,1,0.6))
  
  #read in geospatial data
  file_path = here("data",paste0("mod-2l_10k_K1_phi10_m100_seed1_H50_r60_it--1_t-",i,"_spp-spp_0.csv"))
  gsd_df <- read.csv(file_path)
  gsd_df$env1 <- as.numeric(stringr::str_extract(gsd_df$e, '(?<=, )[^,]+(?=,)')) 
  gsd_df$env2 <- as.numeric(stringr::str_extract(gsd_df$e, '(?<=, )[^,]+(?=\\])')) 
  gsd_df$z1 <- as.numeric(stringr::str_extract(gsd_df$z, '(?<=\\[)[^,]+(?=,)'))
  gsd_df$z2 <- as.numeric(stringr::str_extract(gsd_df$z, '(?<=, )[^,]+(?=\\])')) 
  
  points(i, mean(abs(gsd_df$z1 - gsd_df$env1)*0.1), pch = 1, col = rgb(0,0,1,0.6))
  points(i, mean(abs(gsd_df$z2 - gsd_df$env2)*0.1), pch = 19, col = rgb(0,0,1,0.6))
}
legend("topleft", pch = c(1,19), c("trait 1", "trait 2"))
legend("topright", col = c(rgb(1,0,1,0.6), rgb(0,0,1,0.6)), pch=19,  c("low m (0.25)", "high m (1.00)"))
```

```{r}
plot(1,1,col="white", ylim=c(0,0.04), xlim=c(0,300), xlab="t", ylab="mean(|z - env|*phi)")
for(i in seq(0,300,100)){
  #read in geospatial data
  file_path = here("data",paste0("mod-10k_K5_phi10_m0.25_seed1_H50_r60_it--1_t-",i,"_spp-spp_0.csv"))
  gsd_df <- read.csv(file_path)
  gsd_df$env1 <- as.numeric(stringr::str_extract(gsd_df$e, '(?<=, )[^,]+(?=,)')) 
  gsd_df$env2 <- as.numeric(stringr::str_extract(gsd_df$e, '(?<=, )[^,]+(?=\\])')) 
  gsd_df$z1 <- as.numeric(stringr::str_extract(gsd_df$z, '(?<=\\[)[^,]+(?=,)'))
  gsd_df$z2 <- as.numeric(stringr::str_extract(gsd_df$z, '(?<=, )[^,]+(?=\\])')) 
  
  points(i, mean(abs(gsd_df$z1 - gsd_df$env1)*0.1), pch = 1, col = rgb(1,0,1,0.6))
  points(i, mean(abs(gsd_df$z2 - gsd_df$env2)*0.1), pch = 19, col = rgb(1,0,1,0.6))
  
  #read in geospatial data
  file_path = here("data",paste0("mod-10k_K5_phi10_m1_seed1_H50_r60_it--1_t-",i,"_spp-spp_0.csv"))
  gsd_df <- read.csv(file_path)
  gsd_df$env1 <- as.numeric(stringr::str_extract(gsd_df$e, '(?<=, )[^,]+(?=,)')) 
  gsd_df$env2 <- as.numeric(stringr::str_extract(gsd_df$e, '(?<=, )[^,]+(?=\\])')) 
  gsd_df$z1 <- as.numeric(stringr::str_extract(gsd_df$z, '(?<=\\[)[^,]+(?=,)'))
  gsd_df$z2 <- as.numeric(stringr::str_extract(gsd_df$z, '(?<=, )[^,]+(?=\\])')) 
  
  points(i, mean(abs(gsd_df$z1 - gsd_df$env1)*0.1), pch = 1, col = rgb(0,0,1,0.6))
  points(i, mean(abs(gsd_df$z2 - gsd_df$env2)*0.1), pch = 19, col = rgb(0,0,1,0.6))
}
legend("topleft", pch = c(1,19), c("trait 1", "trait 2"))
legend("topright", col = c(rgb(1,0,1,0.6), rgb(0,0,1,0.6)), pch=19,  c("low m (0.25)", "high m (1.00)"))
```

```{r}
plot(1,1,col="white", ylim=c(0,0.15), xlim=c(0,300), xlab="t", ylab="mean(|z - env|*phi)")
for(i in seq(0,300,100)){
  #read in geospatial data
  file_path = here("data",paste0("mod-10k_K5_phi50_m1_seed1_H50_r60_it--1_t-",i,"_spp-spp_0.csv"))
  gsd_df <- read.csv(file_path)
  gsd_df$env1 <- as.numeric(stringr::str_extract(gsd_df$e, '(?<=, )[^,]+(?=,)')) 
  gsd_df$env2 <- as.numeric(stringr::str_extract(gsd_df$e, '(?<=, )[^,]+(?=\\])')) 
  gsd_df$z1 <- as.numeric(stringr::str_extract(gsd_df$z, '(?<=\\[)[^,]+(?=,)'))
  gsd_df$z2 <- as.numeric(stringr::str_extract(gsd_df$z, '(?<=, )[^,]+(?=\\])')) 
  
  points(i, mean(abs(gsd_df$z1 - gsd_df$env1)*0.5), pch = 1, col = rgb(1,0,1,0.6))
  points(i, mean(abs(gsd_df$z2 - gsd_df$env2)*0.5), pch = 19, col = rgb(1,0,1,0.6))
  
  #read in geospatial data
  file_path = here("data",paste0("mod-10k_K5_phi10_m1_seed1_H50_r60_it--1_t-",i,"_spp-spp_0.csv"))
  gsd_df <- read.csv(file_path)
  gsd_df$env1 <- as.numeric(stringr::str_extract(gsd_df$e, '(?<=, )[^,]+(?=,)')) 
  gsd_df$env2 <- as.numeric(stringr::str_extract(gsd_df$e, '(?<=, )[^,]+(?=\\])')) 
  gsd_df$z1 <- as.numeric(stringr::str_extract(gsd_df$z, '(?<=\\[)[^,]+(?=,)'))
  gsd_df$z2 <- as.numeric(stringr::str_extract(gsd_df$z, '(?<=, )[^,]+(?=\\])')) 
  
  points(i, mean(abs(gsd_df$z1 - gsd_df$env1)*0.1), pch = 1, col = rgb(0,0,1,0.6))
  points(i, mean(abs(gsd_df$z2 - gsd_df$env2)*0.1), pch = 19, col = rgb(0,0,1,0.6))
}
legend("topleft", pch = c(1,19), c("trait 1", "trait 2"))
legend("topright", col = c(rgb(1,0,1,0.6), rgb(0,0,1,0.6)), pch=19,  c("phi = 0.50", "phi = 0.10"))
```

```{r}
i=0


plot(1,1,col="white", ylim=c(0,0.2), xlim=c(0,900), xlab="t", ylab="mean(|z - env|*phi)")
for(i in seq(0,900,100)){
  #read in geospatial data
  file_path = here("data",paste0("mod-mod_K5_phi50_m1_seed1_H50_r60_it--1_t-",i,"_spp-spp_0.csv"))
  gsd_df <- read.csv(file_path)
  gsd_df$env1 <- as.numeric(stringr::str_extract(gsd_df$e, '(?<=, )[^,]+(?=,)')) 
  gsd_df$env2 <- as.numeric(stringr::str_extract(gsd_df$e, '(?<=, )[^,]+(?=\\])')) 
  gsd_df$z1 <- as.numeric(stringr::str_extract(gsd_df$z, '(?<=\\[)[^,]+(?=,)'))
  gsd_df$z2 <- as.numeric(stringr::str_extract(gsd_df$z, '(?<=, )[^,]+(?=\\])')) 
  
  points(i, mean(abs(gsd_df$z1 - gsd_df$env1)*0.5), pch = 19, col = "black")
  
  file_path = here("data",paste0("mod-2l_mod_K5_phi50_m0.25_seed1_H50_r60_it--1_t-",i,"_spp-spp_0.csv"))
  gsd_df <- read.csv(file_path)
  gsd_df$env1 <- as.numeric(stringr::str_extract(gsd_df$e, '(?<=, )[^,]+(?=,)')) 
  gsd_df$env2 <- as.numeric(stringr::str_extract(gsd_df$e, '(?<=, )[^,]+(?=\\])')) 
  gsd_df$z1 <- as.numeric(stringr::str_extract(gsd_df$z, '(?<=\\[)[^,]+(?=,)'))
  gsd_df$z2 <- as.numeric(stringr::str_extract(gsd_df$z, '(?<=, )[^,]+(?=\\])')) 
  
  points(i, mean(abs(gsd_df$z1 - gsd_df$env1)*0.5), pch = 19, col = "blue")
  
}
legend("topright",  col=c("black","blue"), pch = 19, c("sim1: 8 adaptive loci", "sim2: 4 adaptive loci"))
```

```{r}
plot.new()
plot.window(ylim=c(0, 5), xlim = c(-0.5,0.5))
axis(1)
axis(2)
title(ylab="Density")
title(xlab="Phenotypic Mismatch (Phenotype-Temperature)")

for(i in seq(0,900,100)){
  #read in geospatial data
  file_path = here("data",paste0("mod-mod_K5_phi50_m1_seed1_H50_r60_it--1_t-",i,"_spp-spp_0.csv"))
  gsd_df <- read.csv(file_path)
  gsd_df$env1 <- as.numeric(stringr::str_extract(gsd_df$e, '(?<=, )[^,]+(?=,)')) 
  gsd_df$env2 <- as.numeric(stringr::str_extract(gsd_df$e, '(?<=, )[^,]+(?=\\])')) 
  gsd_df$z1 <- as.numeric(stringr::str_extract(gsd_df$z, '(?<=\\[)[^,]+(?=,)'))
  gsd_df$z2 <- as.numeric(stringr::str_extract(gsd_df$z, '(?<=, )[^,]+(?=\\])')) 
  
  polygon(density(gsd_df$z1 - gsd_df$env1), col = rgb(0,1,1,i/1000))
}



```

