---
title: "kmatrices"
output: html_document
---
```{r}
#read in genetic data
file_path = here("data","mod-10k_K5_phi10_m25_seed1_H50_r60_it--1_t-300_spp-spp_0.vcf")
vcf <- read.vcfR(file_path)
x <- vcfR2genlight(vcf) #CHECK THIS
gen_K5_m25 <- as.matrix(x)

#read in genetic data
file_path = here("data","mod-10k_K5_phi10_m1_seed1_H50_r60_it--1_t-300_spp-spp_0.vcf")
vcf <- read.vcfR(file_path)
x <- vcfR2genlight(vcf) #CHECK THIS
gen_K5_m1 <- as.matrix(x)

#read in genetic data
file_path = here("data","mod-10k_K1_phi10_m25_seed1_H50_r60_it--1_t-300_spp-spp_0.vcf")
vcf <- read.vcfR(file_path)
x <- vcfR2genlight(vcf) #CHECK THIS
gen_K1_m25 <- as.matrix(x)

#read in genetic data
file_path = here("data","mod-10k_K1_phi10_m1_seed1_H50_r60_it--1_t-300_spp-spp_0.vcf")
vcf <- read.vcfR(file_path)
x <- vcfR2genlight(vcf) #CHECK THIS
gen_K1_m1 <- as.matrix(x)


genlist <- list()
genlist[[1]] <- gen_K5_m25
genlist[[2]] <- gen_K5_m1
genlist[[3]] <- gen_K1_m25
genlist[[4]] <- gen_K1_m1
```

```{r fig.width=10, fig.width=10}
par(mfrow=c(2,2), oma=rep(0,4), mar=rep(0,4))
for(i in 1:4){
  #FOR TESTING USE SAMPLE OF 100 (!!!COMMENT OUT!!!)
  set.seed(42)
  gen <- genlist[[i]]
  s <- sample(1:nrow(gen),1000)
  gen <- gen[s,]
      
  #make kinship matrix (method = c("astle", "IBS", "vanRaden"))
  Kmatrix <- kinship(gen, method = "astle")
  s <- sample(1:nrow(gen),50)
  Kmatrix <- Kmatrix[s,s]
  diag(Kmatrix) <- NA
  heatmap(Kmatrix, keep.dendro=FALSE, labRow = FALSE, labCol = FALSE)
}
```
```{r}
par(mfrow=c(2,2), oma=rep(0,4), mar=rep(0,4))
for(i in 1:4){
  #FOR TESTING USE SAMPLE OF 100 (!!!COMMENT OUT!!!)
  set.seed(42)
  gen <- genlist[[i]]
  s <- sample(1:nrow(gen),1000)
  gen <- gen[s,]
      
  #make kinship matrix (method = c("astle", "IBS", "vanRaden"))
  Kmatrix <- kinship(gen, method = "IBS")
  s <- sample(1:nrow(gen),50)
  Kmatrix <- Kmatrix[s,s]
  diag(Kmatrix) <- NA
  heatmap(Kmatrix, keep.dendro=FALSE, labRow = FALSE, labCol = FALSE)
}
```
```{r}
par(mfrow=c(2,2), oma=rep(0,4), mar=rep(0,4))
for(i in 1:4){
  #FOR TESTING USE SAMPLE OF 100 (!!!COMMENT OUT!!!)
  set.seed(42)
  gen <- genlist[[i]]
  s <- sample(1:nrow(gen),1000)
  gen <- gen[s,]
      
  #make kinship matrix (method = c("astle", "IBS", "vanRaden"))
  Kmatrix <- kinship(gen, method = "vanRaden")
  s <- sample(1:nrow(gen),50)
  Kmatrix <- Kmatrix[s,s]
  diag(Kmatrix) <- NA
  heatmap(Kmatrix, keep.dendro=FALSE, labRow = FALSE, labCol = FALSE)
}
```


#K test
```{r}
#read in genetic data
file_path = here("data","mod-10k_K5_phi10_m25_seed1_H50_r60_it--1_t-300_spp-spp_0.vcf")
vcf <- read.vcfR(file_path)
x <- vcfR2genlight(vcf) #CHECK THIS
gen_K5_m25 <- as.matrix(x)
rix(x)

#read in genetic data
file_path = here("data","mod-10k_K1_phi10_m25_seed1_H50_r60_it--1_t-300_spp-spp_0.vcf")
vcf <- read.vcfR(file_path)
x <- vcfR2genlight(vcf) #CHECK THIS
gen_K1_m25 <- as.matrix(x)

#read in genetic data
file_path = here("data","mod-10k_K2_phi50_m25_seed1_H50_r60_it--1_t-500_spp-spp_0.vcf")
vcf <- read.vcfR(file_path)
x <- vcfR2genlight(vcf) #CHECK THIS
gen_K2_m25 <- as.matrix(x)


genlist <- list()
genlist[[1]] <- gen_K5_m25
genlist[[2]] <- gen_K1_m25
genlist[[3]] <- gen_K2_m25
```

```{r fig.width=10, fig.width=10}
par(mfrow=c(2,2), oma=rep(0,4), mar=rep(0,4))
for(i in 1:3){
  #FOR TESTING USE SAMPLE OF 100 (!!!COMMENT OUT!!!)
  set.seed(42)
  gen <- genlist[[i]]
  s <- sample(1:nrow(gen),1000)
  gen <- gen[s,]
      
  #make kinship matrix (method = c("astle", "IBS", "vanRaden"))
  Kmatrix <- kinship(gen, method = "astle")
  s <- sample(1:nrow(gen),50)
  Kmatrix <- Kmatrix[s,s]
  diag(Kmatrix) <- NA
  heatmap(Kmatrix, keep.dendro=FALSE, labRow = FALSE, labCol = FALSE)
}
```